#!/bin/bash
set -e

php /var/apache2/config-template.php > /etc/apache2/sites-available/001-reverse-proxy.conf

echo "WTFFFFF $STATIC_APP"
# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

exec apache2 -DFOREGROUND
