# Use node image
FROM php:5.6-apache

# Copy conf files on the server
COPY conf/ /etc/apache2

# Install modules
RUN a2enmod proxy proxy_http

# Set enabled sites to those in the configuration files
RUN a2ensite 000-* 001-*

# Restart apache servier
RUN service apache2 reload